# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftTools' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftTools
  pod 'SnapKit', '~> 5.0.1'
  
  
  pod 'Moya', '~> 14.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'HandyJSON', '~> 5.0.2'
  pod 'ObjectMapper', '~> 3.5'
  
  
  
  pod 'Kingfisher', '~> 5.15.0'
  pod 'Closures', '~> 0.7'
  pod 'FMDB', '~> 2.7.5'
  pod 'ReachabilitySwift', '~> 5.0.0'
  pod 'Starscream', '~> 4.0.4'

  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  
  pod 'JXSegmentedView', '~> 1.2.7'
  pod 'JXPagingView/Paging', '~> 2.0.13'

  pod 'Cache', '~> 6.0.0'
  
  pod 'ZLPhotoBrowser', '~> 4.1.6'
  pod 'NVActivityIndicatorView', '~> 5.1.1'
  pod 'lottie-ios', '3.2.3'
  pod "ESTabBarController-swift", '2.8.0'
  
  #OC
  pod 'FLEX', '4.4.1', :configurations => ['Debug']
  pod 'SVGAPlayer', '~> 2.5.7'
  pod 'MJRefresh', '~> 3.5.0'




 
#  pod 'Moya/RxSwift', '~> 14.0.0-alpha.1'
#  pod 'HandyJSON', :git => 'https://github.com/alibaba/HandyJSON.git'
#  pod 'Then'
#  pod 'NVActivityIndicatorView'
#  pod 'Typist'
#  pod 'SwiftyStoreKit'
#  pod 'Eureka'
#  pod 'ESTabBarController-swift'
#  pod 'MBProgressHUD'
#  pod 'TagListView'
#  pod 'Cosmos'
#  pod 'JXPhotoBrowser/Kingfisher', '2.1.3'
#  pod 'URLNavigator'
#  pod 'MonkeyKing'
#  pod 'Tiercel', '~> 1.2.3'
#  pod 'Repeat'

  
end
